Bump @aws/aurora-dsql-postgresjs-connector from 0.1.1 to 0.1.2 in /packages/postgres-js/example (#125)
Bumps
[@aws/aurora-dsql-postgresjs-connector](https://github.com/awslabs/aurora-dsql-nodejs-connector)
from 0.1.1 to 0.1.2.
<details>
<summary>Release notes</summary>
<p><em>Sourced from <a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/releases"><code>@​aws/aurora-dsql-postgresjs-connector</code>'s
releases</a>.</em></p>
<blockquote>
<h2>aurora-dsql-node-postgres-connector-v0.1.2</h2>
<p>This release exports CommonJS files for consumption by CommonJS
module users.</p>
<p>This avoids import errors like the following, which occurred for
non-ESM imports:</p>
<pre><code>src/index.ts:1:34 - error TS1479: The current file is a
CommonJS module whose imports will produce 'require' calls;
however, the referenced file is an ECMAScript module and cannot be
imported with 'require'. Consider writing a
dynamic 'import(&quot;@aws/aurora-dsql-node-postgres-connector&quot;)'
call instead.
<p>To convert this file to an ECMAScript module, change its file
extension to '.mts' or create a local package.json
file with <code>{ &amp;quot;type&amp;quot;: &amp;quot;module&amp;quot;
}</code>.</p>
<p>1 import { AuroraDSQLClient } from
&quot;<code>@​aws/aurora-dsql-node-postgres-connector</code>&quot;;
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Found 1 error in src/index.ts:1
</code></pre></p>
<h2>What's Changed</h2>
<ul>
<li>Export node-postgres CommonJS module in addition to ES module by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/92">awslabs/aurora-dsql-nodejs-connector#92</a></li>
<li>Run node-postgres example smoke test as part of CI by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/91">awslabs/aurora-dsql-nodejs-connector#91</a></li>
<li>Add job to verify node-postgres versions by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/93">awslabs/aurora-dsql-nodejs-connector#93</a></li>
<li>Bump <code>@​types/node</code> from 24.9.2 to 24.10.0 in
/packages/node-postgres by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/73">awslabs/aurora-dsql-nodejs-connector#73</a></li>
<li>Configure Dependabot to monitor example projects by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/97">awslabs/aurora-dsql-nodejs-connector#97</a></li>
<li>Bump <code>@​types/pg</code> from 8.15.6 to 8.16.0 in
/packages/node-postgres by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/103">awslabs/aurora-dsql-nodejs-connector#103</a></li>
<li>Use non-deprecated testPathPatterns option for jest by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/107">awslabs/aurora-dsql-nodejs-connector#107</a></li>
<li>Bump jest from 29.7.0 to 30.2.0 in /packages/node-postgres/example
by <a
href="https://github.com/dependabot"><code>@​dependabot</code></a>[bot]
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/99">awslabs/aurora-dsql-nodejs-connector#99</a></li>
<li>Upgrade tsdown from 0.11.4 to 0.17.2 by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/108">awslabs/aurora-dsql-nodejs-connector#108</a></li>
<li>Bump versions from 0.1.1 to 0.1.2 by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/109">awslabs/aurora-dsql-nodejs-connector#109</a></li>
<li>Set up trusted publishing for node-postgres by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/114">awslabs/aurora-dsql-nodejs-connector#114</a></li>
<li>Fix node-postgres workflow permissions by <a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/115">awslabs/aurora-dsql-nodejs-connector#115</a></li>
</ul>
<h2>New Contributors</h2>
<ul>
<li><a
href="https://github.com/danielfrankcom"><code>@​danielfrankcom</code></a>
made their first contribution in <a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/pull/92">awslabs/aurora-dsql-nodejs-connector#92</a></li>
</ul>
<p><strong>Full Changelog</strong>: <a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/compare/aurora-dsql-node-postgres-connector-v0.1.1...aurora-dsql-node-postgres-connector-v0.1.2">https://github.com/awslabs/aurora-dsql-nodejs-connector/compare/aurora-dsql-node-postgres-connector-v0.1.1...aurora-dsql-node-postgres-connector-v0.1.2</a></p>
<h2>aurora-dsql-postgresjs-connector-v0.1.2</h2>
<p>This release exports CommonJS files for consumption by CommonJS
module users.</p>
<p>This avoids import errors like the following, which occurred for
non-ESM imports:</p>
<pre><code>src/index.ts(1,36): error TS1479: The current file is a
CommonJS module whose imports will produce 'require' calls;
however, the referenced file is an ECMAScript module and cannot be
imported with 'require'. Consider writing a
dynamic 'import(&quot;@aws/aurora-dsql-postgresjs-connector&quot;)' call
instead.
<p>To convert this file to an ECMAScript module, change its file
extension to '.mts' or create a local package.json
file with <code>{ &amp;quot;type&amp;quot;: &amp;quot;module&amp;quot;
}</code>.</p>
<p>&lt;/tr&gt;&lt;/table&gt;
</code></pre></p>
</blockquote>
<p>... (truncated)</p>
</details>
<details>
<summary>Commits</summary>
<ul>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/7c0873822d1b66ebe60af8bd5b9e51325935da06"><code>7c08738</code></a>
Set up trusted publishing for Postgres.js (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/116">#116</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/c4a3da58ea576f639846f2b555135264bd2cf196"><code>c4a3da5</code></a>
Fix node-postgres workflow permissions (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/115">#115</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/0a0d9ea75d3f5629945fd4df7705506792dddf19"><code>0a0d9ea</code></a>
Set up trusted publishing for node-postgres (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/114">#114</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/f7b633c5b84eb68208aa3635afd25df232d98f8a"><code>f7b633c</code></a>
Bump versions from 0.1.1 to 0.1.2 (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/109">#109</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/df069c0972e0da416aee985478d5cee64c4167d2"><code>df069c0</code></a>
Bump ts-jest from 29.4.5 to 29.4.6 in /packages/postgres-js (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/111">#111</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/c89f0939711868d162eb005f9b8fc698fc241838"><code>c89f093</code></a>
Bump <code>@​typescript-eslint/parser</code> from 8.48.0 to 8.49.0 in
/packages/postgres-js...</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/71c296b911addf3d51f4d2374b29d881cf35ecc4"><code>71c296b</code></a>
Bump <code>@​typescript-eslint/eslint-plugin</code> from 8.48.0 to
8.49.0 in /packages/post...</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/8798ddfe3bef1752228af498513e5a2483390946"><code>8798ddf</code></a>
Upgrade tsdown from 0.11.4 to 0.17.2 (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/108">#108</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/deee35367ab1ed53fcceddba3dd1d3f74d421804"><code>deee353</code></a>
Bump jest from 29.7.0 to 30.2.0 in /packages/postgres-js/example (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/104">#104</a>)</li>
<li><a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/commit/a2bf43fa4069af3d1926bd1aa3b0ddfd4c5d02f7"><code>a2bf43f</code></a>
Bump jest from 29.7.0 to 30.2.0 in /packages/node-postgres/example (<a
href="https://redirect.github.com/awslabs/aurora-dsql-nodejs-connector/issues/99">#99</a>)</li>
<li>Additional commits viewable in <a
href="https://github.com/awslabs/aurora-dsql-nodejs-connector/compare/aurora-dsql-postgresjs-connector-v0.1.1...aurora-dsql-postgresjs-connector-v0.1.2">compare
view</a></li>
</ul>
</details>
<details>
<summary>Maintainer changes</summary>
<p>This version was pushed to npm by [GitHub Actions](<a
href="https://www.npmjs.com/~GitHub">https://www.npmjs.com/~GitHub</a>
Actions), a new releaser for
<code>@​aws/aurora-dsql-postgresjs-connector</code> since your current
version.</p>
</details>
<br />


[![Dependabot compatibility
score](https://dependabot-badges.githubapp.com/badges/compatibility_score?dependency-name=@aws/aurora-dsql-postgresjs-connector&package-manager=npm_and_yarn&previous-version=0.1.1&new-version=0.1.2)](https://docs.github.com/en/github/managing-security-vulnerabilities/about-dependabot-security-updates#about-compatibility-scores)

Dependabot will resolve any conflicts with this PR as long as you don't
alter it yourself. You can also trigger a rebase manually by commenting
`@dependabot rebase`.

[//]: # (dependabot-automerge-start)
[//]: # (dependabot-automerge-end)

---

<details>
<summary>Dependabot commands and options</summary>
<br />

You can trigger Dependabot actions by commenting on this PR:
- `@dependabot rebase` will rebase this PR
- `@dependabot recreate` will recreate this PR, overwriting any edits
that have been made to it
- `@dependabot merge` will merge this PR after your CI passes on it
- `@dependabot squash and merge` will squash and merge this PR after
your CI passes on it
- `@dependabot cancel merge` will cancel a previously requested merge
and block automerging
- `@dependabot reopen` will reopen this PR if it is closed
- `@dependabot close` will close this PR and stop Dependabot recreating
it. You can achieve the same result by closing it manually
- `@dependabot show <dependency name> ignore conditions` will show all
of the ignore conditions of the specified dependency
- `@dependabot ignore this major version` will close this PR and stop
Dependabot creating any more for this major version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this minor version` will close this PR and stop
Dependabot creating any more for this minor version (unless you reopen
the PR or upgrade to it yourself)
- `@dependabot ignore this dependency` will close this PR and stop
Dependabot creating any more for this dependency (unless you reopen the
PR or upgrade to it yourself)


</details>

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>